name: Checks

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    uses: rbcorrales/wpvdb-scripts/.github/workflows/plugin-ci.yml@main
    with:
      composer-install: true
      bun-install: true
      bun-lint-command: bun run lint
      build-command: bun run build
